
export const BRAZILIAN_CITIES = [
  "Abadia de Goiás, GO",
  "Acrelândia, AC",
  "Água Branca, AL",
  "Água Clara, MS",
  "Água Fria, BA",
  "Águas Lindas de Goiás, GO",
  "Aiquara, BA",
  "Alagoinhas, BA",
  "Alcobaça, BA",
  "Alegrete, RS",
  "Alfenas, MG",
  "Alfredo Chaves, ES",
  "Almeirim, PA",
  "Almenara, MG",
  "Almirante Tamandaré, PR",
  "Aloândia, GO",
  "Alta Floresta, MT",
  "Altamira, PA",
  "Alto Araguaia, MT",
  "Alto Horizonte, GO",
  "Alto Paraguai, MT",
  "Alto Parnaíba, MA",
  "Alvorada, RS",
  "Amajari, RR",
  "Amambai, MS",
  "Amapá, AP",
  "Amaralina, GO",
  "Americana, SP",
  "Américo Brasiliense, SP",
  "Ametista do Sul, RS",
  "Anápolis, GO",
  "Ananindeua, PA",
  "Anapu, PA",
  "Andradina, SP",
  "Angra dos Reis, RJ",
  "Antônio João, MS",
  "Aparecida de Goiânia, GO",
  "Aparecida do Taboado, MS",
  "Apucarana, PR",
  "Apuí, AM",
  "Aracaju, SE",
  "Araçatuba, SP",
  "Aracruz, ES",
  "Aragarças, GO",
  "Araguaína, TO",
  "Aral Moreira, MS",
  "Aramari, BA",
  "Araraquara, SP",
  "Araras, SP",
  "Arari, MA",
  "Aripuanã, MT",
  "Ariquemes, RO",
  "Assis, SP",
  "Assis Chateaubriand, PR",
  "Atibaia, SP",
  "Augusto Corrêa, PA",
  "Avaré, SP",
  "Bagé, RS",
  "Bálsamo, SP",
  "Balsas, MA",
  "Bandeirantes, MS",
  "Barcarena, PA",
  "Barra de São Francisco, ES",
  "Barra do Bugres, MT",
  "Barra do Garças, MT",
  "Barra do Piraí, RJ",
  "Barreiras, BA",
  "Barretos, SP",
  "Barueri, SP",
  "Bauru, SP",
  "Bela Vista, MS",
  "Bela Vista de Goiás, GO",
  "Belém, PA",
  "Belford Roxo, RJ",
  "Belo Horizonte, MG",
  "Benevides, PA",
  "Bento Gonçalves, RS",
  "Betim, MG",
  "Blumenau, SC",
  "Boa Vista, RR",
  "Bocaiúva, MG",
  "Bodoquena, MS",
  "Bom Jesus da Lapa, BA",
  "Bom Jesus, PI",
  "Bonito, MS",
  "Bragança, PA",
  "Bragança Paulista, SP",
  "Brasília, DF",
  "Brasil Novo, PA",
  "Brasnorte, MT",
  "Breu Branco, PA",
  "Brumado, BA",
  "Buriticupu, MA",
  "Caarapó, MS",
  "Cáceres, MT",
  "Cachoeira do Sul, RS",
  "Cachoeiro de Itapemirim, ES",
  "Caculé, BA",
  "Caetité, BA",
  "Camaçari, BA",
  "Camapuã, MS",
  "Cambé, PR",
  "Campina Grande, PB",
  "Campinas, SP",
  "Campo Grande, MS",
  "Campo Mourão, PR",
  "Campo Novo do Parecis, MT",
  "Campo Verde, MT",
  "Campos dos Goytacazes, RJ",
  "Canarana, MT",
  "Canguçu, RS",
  "Canoas, RS",
  "Capanema, PA",
  "Capitão Poço, PA",
  "Caracaraí, RR",
  "Carapicuíba, SP",
  "Caratinga, MG",
  "Carazinho, RS",
  "Caruaru, PE",
  "Cascavel, PR",
  "Castanhal, PA",
  "Castro, PR",
  "Catalão, GO",
  "Catanduva, SP",
  "Caxias do Sul, RS",
  "Caxias, MA",
  "Cerejeiras, RO",
  "Chapecó, SC",
  "Cianorte, PR",
  "Cidelândia, MA",
  "Cláudia, MT",
  "Coari, AM",
  "Codó, MA",
  "Colatina, ES",
  "Colíder, MT",
  "Colinas do Tocantins, TO",
  "Colorado do Oeste, RO",
  "Comodoro, MT",
  "Conceição do Araguaia, PA",
  "Confresa, MT",
  "Conselheiro Lafaiete, MG",
  "Contagem, MG",
  "Corumbá, MS",
  "Corumbá de Goiás, GO",
  "Corumbiara, RO",
  "Coruripe, AL",
  "Coxim, MS",
  "Criciúma, SC",
  "Cristalina, GO",
  "Cruz Alta, RS",
  "Cruzeiro do Sul, AC",
  "Cubatão, SP",
  "Cuiabá, MT",
  "Curionópolis, PA",
  "Curitiba, PR",
  "Curvelo, MG",
  "Deodápolis, MS",
  "Diamantino, MT",
  "Divinópolis, MG",
  "Dom Eliseu, PA",
  "Dois Vizinhos, PR",
  "Douradina, MS",
  "Dourados, MS",
  "Duque de Caxias, RJ",
  "Eldorado dos Carajás, PA",
  "Eldorado, MS",
  "Erechim, RS",
  "Espírito Santo do Pinhal, SP",
  "Eunápolis, BA",
  "Feira de Santana, BA",
  "Fernandópolis, SP",
  "Florianópolis, SC",
  "Formiga, MG",
  "Formosa do Rio Preto, BA",
  "Formosa, GO",
  "Fortaleza, CE",
  "Foz do Iguaçu, PR",
  "Franca, SP",
  "Francisco Beltrão, PR",
  "Garanhuns, PE",
  "Goiânia, GO",
  "Goianésia, GO",
  "Goiatuba, GO",
  "Governador Valadares, MG",
  "Grajaú, MA",
  "Guanambi, BA",
  "Guarda-Mor, MG",
  "Guarantã do Norte, MT",
  "Guarapari, ES",
  "Guarapuava, PR",
  "Guaratinguetá, SP",
  "Guarujá, SP",
  "Guarulhos, SP",
  "Ibirité, MG",
  "Ibotirama, BA",
  "Ijuí, RS",
  "Ilhéus, BA",
  "Imperatriz, MA",
  "Indaiatuba, SP",
  "Ipatinga, MG",
  "Ipirá, BA",
  "Iporá, GO",
  "Irecê, BA",
  "Itaberaí, GO",
  "Itabira, MG",
  "Itabuna, BA",
  "Itacoatiara, AM",
  "Itaguaí, RJ",
  "Itaituba, PA",
  "Itajaí, SC",
  "Itamaraju, BA",
  "Itapetinga, BA",
  "Itapeva, SP",
  "Itaporã, MS",
  "Itaqui, RS",
  "Itumbiara, GO",
  "Iturama, MG",
  "Jaboatão dos Guararapes, PE",
  "Jaboticabal, SP",
  "Jacareí, SP",
  "Jaguaquara, BA",
  "Jaguaré, ES",
  "Jales, SP",
  "Janaúba, MG",
  "Jandira, SP",
  "Jaraguá do Sul, SC",
  "Jaraguá, GO",
  "Jaru, RO",
  "Jataí, GO",
  "Jaú, SP",
  "Jequié, BA",
  "Ji-Paraná, RO",
  "João Monlevade, MG",
  "João Pessoa, PB",
  "João Pinheiro, MG",
  "Joinville, SC",
  "Juara, MT",
  "Juazeiro do Norte, CE",
  "Juazeiro, BA",
  "Juína, MT",
  "Juiz de Fora, MG",
  "Jundiaí, SP",
  "Lages, SC",
  "Laguna Carapã, MS",
  "Laranjeiras do Sul, PR",
  "Lavras, MG",
  "Lençóis Paulista, SP",
  "Limeira, SP",
  "Linhares, ES",
  "Lins, SP",
  "Londrina, PR",
  "Lucas do Rio Verde, MT",
  "Luís Eduardo Magalhães, BA",
  "Macapá, AP",
  "Macaé, RJ",
  "Maceió, AL",
  "Manaus, AM",
  "Marabá, PA",
  "Maracaju, MS",
  "Maracanaú, CE",
  "Maringá, PR",
  "Marituba, PA",
  "Matão, SP",
  "Matinhos, PR",
  "Matupá, MT",
  "Mauá, SP",
  "Medianeira, PR",
  "Mineiros, GO",
  "Mirassol d'Oeste, MT",
  "Mogi das Cruzes, SP",
  "Mogi Guaçu, SP",
  "Montes Claros, MG",
  "Morrinhos, GO",
  "Mossoró, RN",
  "Mundo Novo, MS",
  "Natal, RN",
  "Naviraí, MS",
  "Niquelândia, GO",
  "Niterói, RJ",
  "Nobres, MT",
  "Nossa Senhora do Socorro, SE",
  "Nova Alvorada do Sul, MS",
  "Nova Andradina, MS",
  "Nova Friburgo, RJ",
  "Nova Iguaçu, RJ",
  "Nova Lima, MG",
  "Nova Mutum, MT",
  "Nova Odessa, SP",
  "Nova Olímpia, MT",
  "Nova Prata, RS",
  "Nova Ubiratã, MT",
  "Nova Venécia, ES",
  "Novo Hamburgo, RS",
  "Novo Progresso, PA",
  "Oiapoque, AP",
  "Olinda, PE",
  "Orlândia, SP",
  "Oriximiná, PA",
  "Osasco, SP",
  "Ouro Preto do Oeste, RO",
  "Palmas, TO",
  "Palmeira das Missões, RS",
  "Paracatu, MG",
  "Paragominas, PA",
  "Paranaíba, MS",
  "Paranaguá, PR",
  "Paranatinga, MT",
  "Parauapebas, PA",
  "Parnaíba, PI",
  "Passo Fundo, RS",
  "Passos, MG",
  "Pato Branco, PR",
  "Patos de Minas, MG",
  "Patrocínio, MG",
  "Paulínia, SP",
  "Paulo Afonso, BA",
  "Pederneiras, SP",
  "Pedra Preta, MT",
  "Pelotas, RS",
  "Petrolina, PE",
  "Petrópolis, RJ",
  "Pimenta Bueno, RO",
  "Pindamonhangaba, SP",
  "Pinheiro, MA",
  "Piracicaba, SP",
  "Pirassununga, SP",
  "Poá, SP",
  "Poços de Caldas, MG",
  "Poconé, MT",
  "Ponta Grossa, PR",
  "Ponta Porã, MS",
  "Pontes e Lacerda, MT",
  "Portel, PA",
  "Porto Alegre, RS",
  "Porto dos Gaúchos, MT",
  "Porto Ferreira, SP",
  "Porto Nacional, TO",
  "Porto Seguro, BA",
  "Porto Velho, RO",
  "Pouso Alegre, MG",
  "Primavera do Leste, MT",
  "Presidente Dutra, MA",
  "Presidente Prudente, SP",
  "Promissão, SP",
  "Querência, MT",
  "Recife, PE",
  "Redenção, PA",
  "Registro, SP",
  "Resende, RJ",
  "Ribeirão das Neves, MG",
  "Ribeirão Pires, SP",
  "Ribeirão Preto, SP",
  "Rio Branco, AC",
  "Rio Brilhante, MS",
  "Rio Claro, SP",
  "Rio de Janeiro, RJ",
  "Rio Grande, RS",
  "Rio Verde de Mato Grosso, MS",
  "Rio Verde, GO",
  "Rolim de Moura, RO",
  "Rondonópolis, MT",
  "Rurópolis, PA",
  "Sabinópolis, MG",
  "Salinópolis, PA",
  "Salto, SP",
  "Salvador, BA",
  "Santa Cruz do Rio Pardo, SP",
  "Santa Cruz do Sul, RS",
  "Santa Helena de Goiás, GO",
  "Santa Inês, MA",
  "Santa Maria da Vitória, BA",
  "Santa Maria, RS",
  "Santa Rita do Passa Quatro, SP",
  "Santa Rita do Pardo, MS",
  "Santarém, PA",
  "Santana do Araguaia, PA",
  "Santana do Livramento, RS",
  "Santana, AP",
  "Santo Ângelo, RS",
  "Santo André, SP",
  "Santo Antônio de Jesus, BA",
  "Santos, SP",
  "São Bento do Sul, SC",
  "São Bernardo do Campo, SP",
  "São Borja, RS",
  "São Caetano do Sul, SP",
  "São Carlos, SP",
  "São Félix do Araguaia, MT",
  "São Félix do Xingu, PA",
  "São Francisco do Sul, SC",
  "São Gabriel da Cachoeira, AM",
  "São Gabriel do Oeste, MS",
  "São Gonçalo, RJ",
  "São João da Boa Vista, SP",
  "São João de Meriti, RJ",
  "São Joaquim da Barra, SP",
  "São José de Ribamar, MA",
  "São José do Rio Preto, SP",
  "São José dos Campos, SP",
  "São José dos Pinhais, PR",
  "São José, SC",
  "São Leopoldo, RS",
  "São Luís, MA",
  "São Mateus do Sul, PR",
  "São Mateus, ES",
  "São Miguel do Araguaia, GO",
  "São Miguel do Guamá, PA",
  "São Miguel do Iguaçu, PR",
  "São Paulo, SP",
  "São Vicente, SP",
  "Sapiranga, RS",
  "Sapezal, MT",
  "Senhor do Bonfim, BA",
  "Serra, ES",
  "Serrana, SP",
  "Sertãozinho, SP",
  "Sete Lagoas, MG",
  "Sidrolândia, MS",
  "Sinop, MT",
  "Sobral, CE",
  "Sorocaba, SP",
  "Sorriso, MT",
  "Sumaré, SP",
  "Tabatinga, AM",
  "Tucumã, PA",
  "Tucuruí, PA",
  "Tupã, SP",
  "Tailândia, PA",
  "Tangará da Serra, MT",
  "Tapejara, RS",
  "Tapes, RS",
  "Taquari, RS",
  "Tatuí, SP",
  "Taubaté, SP",
  "Tefé, AM",
  "Teixeira de Freitas, BA",
  "Teófilo Otoni, MG",
  "Teresina, PI",
  "Teresópolis, RJ",
  "Timon, MA",
  "Toledo, PR",
  "Três Corações, MG",
  "Três de Maio, RS",
  "Três Lagoas, MS",
  "Três Passos, RS",
  "Trindade, GO",
  "Tubarão, SC",
  "Uberaba, MG",
  "Uberlândia, MG",
  "Umuarama, PR",
  "Unaí, MG",
  "Uruaçu, GO",
  "Uruará, PA",
  "Uruguaiana, RS",
  "Valença, BA",
  "Valinhos, SP",
  "Valparaíso de Goiás, GO",
  "Várzea Grande, MT",
  "Varginha, MG",
  "Venâncio Aires, RS",
  "Vera, MT",
  "Viamão, RS",
  "Viana, ES",
  "Vilhena, RO",
  "Vitória da Conquista, BA",
  "Vitória de Santo Antão, PE",
  "Vitória, ES",
  "Volta Redonda, RJ",
  "Votuporanga, SP",
  "Xinguara, PA",
];
